
image:
batch: 64
vit_checkpoint: outputs/vit_ship_classifier_final.pth
vit_config: configs/vit.yaml
unet_checkpoint: outputs/unet_ship_segmenter_final.pth
unet_config: configs/unet.yaml
patch_size: 224
overlap: 32
batch-size: 32
confidence_threshold: 0.5
device: cuda
formats: ['mask', 'json', 'overlay']
save_patches: false
use_s3: false
s3_bucket: