# ViT Ship Classifier Configuration

model:
  name: vit_base_patch16_224  # Options: vit_small_patch16_224, vit_base_patch16_224, vit_large_patch16_224
  pretrained: true  # Use ImageNet pretrained weights
  freeze_backbone_epochs: 3  # Freeze backbone for first N epochs (0 to disable)
  download: false
  local_weights_path: model_states


training:
  batch_size: 128  # Reduce if GPU OOM
  max_epochs: 40
  early_stopping_patience: 7
  pos_weight: 4.0  # Weight for positive class (ships) to handle imbalance
  use_weighted_sampler: true  # Use weighted sampling for class balance
  precision: 16  # Mixed precision training (16 or 32)

  # Ship-specific training settings
  small_ship_focus: true  # Apply additional augmentations for small ships
  mixup_alpha: 0.2  # Data augmentation to improve generalization

optimizer:
  name: adamw  # Options: adam, adamw
  lr: 0.00008  # Initial learning rate
  weight_decay: 0.02  # L2 regularization

scheduler:
  name: cosine  # Options: cosine, reduce_on_plateau
  T_max: 30  # For cosine annealing (should match max_epochs)
  eta_min: 0.0000001  # Minimum learning rate
  warmup_epochs: 5  # Learning rate warmup
  # For reduce_on_plateau:
  # factor: 0.5
  # patience: 5
  # min_lr: 0.0000001

augmentation:
  hflip_prob: 0.5  # Horizontal flip probability
  vflip_prob: 0.5  # Vertical flip probability
  rotation: true  # Random 90-degree rotations
  color_jitter: true  # Color augmentation

  # Additional augmentations for ship preservation
  gaussian_blur_prob: 0.1  # Light blur to simulate atmospheric effects
  brightness_range: [0.8, 1.2]  # Conservative brightness changes
  contrast_range: [0.9, 1.1]  # Conservative contrast changes

  # Ship-specific augmentations
  ship_aware_crop: true
  preserv_small_objects: true

data:
  manifest_path: data\airbus-ship-detection\train_ship_segmentations_v2.csv

  val_split: 0.2  # Validation set proportion
  num_workers: 4  # DataLoader workers
  random_seed: 42  # For reproducibility

  # Preprocessing settings
  preprocessing_method: adaptive  # Options: standard, adaptive, multiscale
  target_size: 224
  interpolation: area
  apply_sharpening: true
  sharpening_strength: 0.3

  # Data filtering
  min_ship_pixel_ratio: 0.001  # Keep very small ships
  max_background_ratio: 0.95

# Evaluation settings
evaluation:
  use_sliding_window: true  # For inference on 768x768 images
  ensemble_predictions: true
  confidence_threshold: 0.4  # Lower threshold for small ships

# Alternative lightweight config for testing
# model:
#   name: vit_tiny_patch16_224  # Smaller model
#   pretrained: true
#   freeze_backbone_epochs: 0
# 
# training:
#   batch_size: 64
#   max_epochs: 5
#   early_stopping_patience: 3
#   pos_weight: 1.0
#   use_weighted_sampler: false
#   precision: 32